### ISSUE TITLE
训练ROD-Net遇到的问题

### ISSUE THREAD

**Issue by RouChan** [Zhuanglong2/T-RODNet#4]
你好，最近我在尝试训练RODNet，遇到一些问题，希望能获得你的解答。

原作者论文里面，预测得到的ConfMaps最后要调用L-NMS模块获得物体类型和位置的信息，但是我好像没有看到调用L-NMS函数处理的接口。

希望能获得解答

**Comment by Zhuanglong2** [comment]
> 你好，最近我在尝试训练RODNet，遇到一些问题，希望能获得你的解答。
> 
> 原作者论文里面，预测得到的ConfMaps最后要调用L-NMS模块获得物体类型和位置的信息，但是我好像没有看到调用L-NMS函数处理的接口。
> 
> 希望能获得解答
Hi，

We are sorry for our delayed reply. The L-NMS module is adopted in "the postprocess.py".

Best wish,
Long Zhuang
