### ISSUE TITLE
Graphical prediction results

### ISSUE THREAD

**Issue by promaxj** [Zhuanglong2/T-RODNet#6]
Thanks for sharing your code!

============================================================
When I tried to graph the results, use "visualize_test_img" function
found that the predicted radar point is not on the ConfMap of the object, 
but always appears at the bottom right.

As shown in the figure below
![image](https://user-images.githubusercontent.com/6398533/210078607-aec5e6d2-04d1-44e8-8489-4de1727738b5.png)

**Comment by Zhuanglong2** [comment]
> Thanks for sharing your code!
> 
> ============================================================ When I tried to graph the results, use "visualize_test_img" function found that the predicted radar point is not on the ConfMap of the object, but always appears at the bottom right.
> 
> As shown in the figure below ![image](https://user-images.githubusercontent.com/6398533/210078607-aec5e6d2-04d1-44e8-8489-4de1727738b5.png)

Hi,

We have updated our code and addressed this bug. You can try it again. We are sorry for our late response. We didn't see your question first.

Best wish,

Long Zhuang.
