### ISSUE TITLE
Question about test：KeyError: 'model_name'

### ISSUE THREAD

**Issue by langsaoderensheng** [Zhuanglong2/T-RODNet#7]
Hi, I recently read your paper ,and found it very inspiring. But something went wrong during the test.
looking forward to an answer.

File "E:/new/T-RODNet/tools/test.py", line 109, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "E:/new/T-RODNet/tools/test.py", line 109, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'model_name'

**Comment by Zhuanglong2** [comment]
> 

Hello, thank you for your attention.
You need to write your checkpoint file path on line 31.

**Comment by Zhuanglong2** [comment]
> Thank you for your reply, I have written the checkpoint file path on line 31, can you help me check if it is correct? Thanks parser.add_argument('--checkpoint', type=str,default=r'E:\new\T-RODNet\data\checkpoints\T_RODNet-20230515-144746\epoch_60_final.pkl', help='path to the saved trained model')

Please change lines 330 and 336 in train.py to the following form:
 'model_state_dict': net.state_dict(),    
 save_model_path = '%s/epoch_%02d_final.pth' % (model_dir, epoch + 1)

I find your checkpoint file is ".pkl". In fact, our test file needs to be ".pth". Please try again according to the above operation. Also, you can try it with "epoch_1_final.pth" and test it more quickly.

Thank you for your problem again.

**Comment by Zhuanglong2** [comment]
> I tried this method and I changed .pkl to .pth before, but the error is still not resolved

Please send your ".pth" file to my personal email longzhuang21@126.com. I will tell you how to do after I test this file.

We are sorry for our code problem.

**Comment by Zhuanglong2** [comment]
Hi,

I have got your ".pth" file and it cannot work. But I have addressed this problem and other bugs in graph visualization. Also, I have updated our code. Please re-download our code and train again.

Best wish,
Long Zhuang

**Comment by langsaoderensheng** [comment]
Thank you very much, I wish you a lot of success
&nbsp;


3126376538
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Zhuanglong2/T-RODNet] Question about test：KeyError: &#39;model_name&#39; (Issue #7)






你好

我有你的“.pth”文件，它不能工作。但我已经解决了这个问题和图形可视化中的其他错误。另外，我已经更新了我们的代码。请重新下载我们的代码和训练。

最好的祝愿，
龙庄

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.
